package net.bouzuya.nekurabe.data.migration

import android.database.Cursor
import androidx.sqlite.db.SupportSQLiteDatabase
import net.bouzuya.nekurabe.data.OffsetDateTimeConverter
import org.junit.Assert
import org.threeten.bp.OffsetDateTime


fun testItemsTable(database: SupportSQLiteDatabase) {
    val name = "name1"
    val createdAt = OffsetDateTime.now()
    val updatedAt = createdAt.plusMinutes(5)

    database.execSQL(
        "INSERT INTO items(name, created_at, updated_at) VALUES(?, ?, ?)",
        arrayOf(
            name,
            OffsetDateTimeConverter().toLong(createdAt),
            OffsetDateTimeConverter().toLong(updatedAt)
        )
    )

    val autoGeneratedId = 1L
    val cursor = database.query(
        "SELECT id, name, created_at, updated_at FROM items WHERE id = ?",
        arrayOf(autoGeneratedId)
    )
    cursor.moveToNext()
    Assert.assertEquals(autoGeneratedId, cursor.getLong(0)) // id
    Assert.assertEquals(name, cursor.getString(1)) // name
    Assert.assertEquals(createdAt, cursor.getOffsetDateTime(2)) // created_at
    Assert.assertEquals(updatedAt, cursor.getOffsetDateTime(3)) // updated_at
}

fun testStoresTable(database: SupportSQLiteDatabase) {
    val name = "name1"
    val createdAt = OffsetDateTime.now()
    val updatedAt = createdAt.plusMinutes(5)

    database.execSQL(
        "INSERT INTO stores(name, created_at, updated_at) VALUES(?, ?, ?)",
        arrayOf(
            name,
            OffsetDateTimeConverter().toLong(createdAt),
            OffsetDateTimeConverter().toLong(updatedAt)
        )
    )

    val autoGeneratedId = 1L
    val cursor = database.query(
        "SELECT id, name, created_at, updated_at FROM stores WHERE id = ?",
        arrayOf(autoGeneratedId)
    )
    cursor.moveToNext()
    Assert.assertEquals(autoGeneratedId, cursor.getLong(0)) // id
    Assert.assertEquals(name, cursor.getString(1)) // name
    Assert.assertEquals(createdAt, cursor.getOffsetDateTime(2)) // created_at
    Assert.assertEquals(updatedAt, cursor.getOffsetDateTime(3)) // updated_at
}

fun Cursor.getOffsetDateTime(columnIndex: Int): OffsetDateTime =
    OffsetDateTimeConverter().fromLong(getLong(columnIndex))
